// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-QX-b_hn_5LEXfeV_S0ba9nCKDloSypY',
    appId: '1:523850795704:web:f8bad7f1d62f562be6c24d',
    messagingSenderId: '523850795704',
    projectId: 'al-manara-library',
    authDomain: 'al-manara-library.firebaseapp.com',
    storageBucket: 'al-manara-library.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT4Lcb-DExeDLQl3zZcg06mN-3es9-VMY',
    appId: '1:523850795704:android:ee18287f7dadf7e6e6c24d',
    messagingSenderId: '523850795704',
    projectId: 'al-manara-library',
    storageBucket: 'al-manara-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT5Wjchj53uv53lEBFfBFDGXMFPr7dsMo',
    appId: '1:523850795704:ios:bc0584aa560c74ade6c24d',
    messagingSenderId: '523850795704',
    projectId: 'al-manara-library',
    storageBucket: 'al-manara-library.firebasestorage.app',
    iosBundleId: 'com.example.alManaraSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT5Wjchj53uv53lEBFfBFDGXMFPr7dsMo',
    appId: '1:523850795704:ios:bc0584aa560c74ade6c24d',
    messagingSenderId: '523850795704',
    projectId: 'al-manara-library',
    storageBucket: 'al-manara-library.firebasestorage.app',
    iosBundleId: 'com.example.alManaraSystem',
  );
}
